-- 1. TABLE CREATION

CREATE DATABASE EMPLOYEE;
USE EMPLOYEE;

CREATE TABLE DEPARTMENTS
(DEPARTMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
DEPARTMENT_NAME VARCHAR(100) NOT NULL UNIQUE);
ALTER TABLE DEPARTMENTS AUTO_INCREMENT=101;

CREATE TABLE LOCATION 
(LOCATION_ID INT PRIMARY KEY AUTO_INCREMENT,
LOCATION VARCHAR(30) NOT NULL UNIQUE);
ALTER TABLE LOCATION AUTO_INCREMENT=1001;

CREATE TABLE EMPLOYEES
(EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,
EMPLOYEE_NAME VARCHAR(50) NOT NULL,
GENDER ENUM('M','F') NOT NULL,
AGE INT CHECK(age>=18),
HIRE_DATE DATE DEFAULT(CURRENT_DATE),
DEPARTMENT_ID INT,
LOCATION_ID INT,
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID));

DESC DEPARTMENTS;
DESC LOCATION;
DESC EMPLOYEES;


-- 2.TABLE ALTERATION

ALTER TABLE EMPLOYEES ADD EMAIL VARCHAR(100) NOT NULL UNIQUE;
ALTER TABLE EMPLOYEES ADD DESIGNATION VARCHAR(100);
ALTER TABLE EMPLOYEES MODIFY DESIGNATION VARCHAR(200);
ALTER TABLE EMPLOYEES DROP COLUMN AGE;
ALTER TABLE EMPLOYEES RENAME COLUMN HIRE_DATE TO DATE_OF_JOINING;
 
DESC EMPLOYEES;


-- 3.TABLE RENAMING

RENAME TABLE DEPARTMENTS TO DEPARTMENT_INFO;
RENAME TABLE LOCATION TO LOCATIONS;

SHOW TABLES; 


-- 4. TABLE TRUNCATION

TRUNCATE TABLE EMPLOYEES;
DESC EMPLOYEES;


-- 5. DATABASE AND TABLE DROPPING

DROP TABLE EMPLOYEES;
SHOW TABLES;

DROP DATABASE EMPLOYEE;
